---
title: "Data Manipulation"
output: github_document
---

I'm an R Markdown document! 

```{r setup, echo = FALSE,message = FALSE}
library(tidyverse)
```

This document will show how to do data manipulation.

Import the two datasets that we are going to manipulate

```{r}
litters_df =
  read_csv("data/FAS_litters.csv",na = c("NA","",".") )

litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv",na = c("NA","","."))

pups_df = janitor::clean_names(pups_df)
```

## `select` works on columns

Use `select()` to select variables
You can choose the variables that you need and get the only them in your dataset

```{r}
select(litters_df,group,litter_number,gd0_weight)
```
choose from group to gd18
```{r}
select(litters_df,group:gd18_weight)
```
deselect from group to gd18
```{r}
select(litters_df,-(group:gd18_weight))
```

```{r}
select(litters_df,starts_with("gd")) # choose variables starts with gd

select(litters_df,contains("pups")) # choose variables that contains pups
```

```{r}
select(litters_df,GROUP = group) 

rename(litters_df,GROUP = group)

select(litters_df,litter_number,gd0_weight,everything()) # rearrange the shunxu of variables

relocate(litters_df,litter_number,gd0_weight)
```
```{r}
select(pups_df,litter_number,sex,pd_ears)
```

## `filter` works on rows

```{r}
filter(litters_df,gd_of_birth == 20) # choose the rows with gd_of_birth == 20

filter(litters_df,pups_born_alive > 8)
```

```{r}
filter(litters_df,pups_born_alive != 9)
```

```{r}
filter(litters_df,group == "Low8")
filter(litters_df,group %in% c("Low8","Low7")) # what doews %in% mean
# filter(litters_df,group == c("Low8","Low7")) why is this incorrect
```

```{r}
filter(litters_df,group %in% c("Low8","Low7"),pups_born_alive == 8) 
# a and b are true
filter(litters_df,group %in% c("Low8","Low7")|pups_born_alive == 8)
# either or b is true
```
```{r}
drop_na(litters_df) # drop the row with any NA inside

drop_na(litters_df,gd0_weight) # drop the row with NA inside gd0_weight
```




## `mutate`


## `arrange`

